version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
volumes:
  postgres-data:
